# Site Configuration
site:
    # Site title and tagine
    title: "Cucine Povere"
    tagline: "an engineers take on italian cuisine"

    # Site logo (should be stored in the `public` directory)
    logo: "logo.png"

    # Date format, see https://stackoverflow.com/a/20234207/1720829
    date_format: "January 02, 2006"

# Author Configuration (you can override this per post with post meta data)
#
# This is the default Author for all posts unless specified in a markdown files meta data
author:
    name: "Nathan Fiscaletti"
    bio: "Pasta Enthusiast"
    avatar: "me.jpg"